### ISSUE TITLE
A way to install mygui with multiple rendersystems support at the same time

### ISSUE THREAD

**Issue by AMDmi3** [MyGUI/mygui#102]
I'm maintainer of FreeBSD port of mygui and I have a problem caused by the fact that mygui selection of render systems is mutually exclusive. That is, one consumer port (say, rigs of rods) need Ogre3D rendersystem, and another (say, openwm) needs dummy rendersystem (I'm not sure whether openmw will work with ogre-enabled mygui, but even if it does, we still don't want to pull in ogre3d needlessly).

So, if possible, I need a hint on how to handle this gracefully. My guess is that it could be possible to build rendersystem-dependent parts separately, e.g. have "mygui" port with rendersystem-agnostic bits, and "mygui-dummy" / "mygui-ogre3d" with rendersystem-specific ones.

Since the ports are built separately, I'd need to exclude rendersystem-specific bits from "mygui" build, and for "mygui-dummy" / "mygui-ogre3d" I'll need to only build specific bits. Any idea on how to achieve that most easily?

Or is my guess completely wrong and rendersystem affects the whole build, so partial builds are not possible at all? Any other ideas?

**Comment by Altren** [comment]
I'm not sure that I clearly understand your problem, but here's how I think you can build several render systems and keep them independent.

Do two (or more if you need more different render systems) out of source builds with ogre3d and dummy render system. Then use MyGUIEngine headers and libs in libmygui-dev package (copy it from any build, since those will be exactly same regardless or render system), and use platform specific headers and lib from two other packages (libmygui.ogreplatform-dev libmygui.dummyplatform-dev). Don't know how packages are named in FreeBSD, I used those that are currently used in debian and ubuntu.

**Comment by AMDmi3** [comment]
There are no packages, as I'm creating ones, and I want to avoid building the same sources multiple times needlessly.

My idea was roughly the following:
- Main package (e.g. libmygui-dev): build with MYGUI_RENDERSYSTEM=1 (or 0 to not build any render system at all), put everything which is platform-agnostic into the package
- Ogre platform (libmygui.ogreplatform-dev): run cmake with MYGUI_RENDERSYSTEM=3 and run make/make install only in Platforms/Ogre/OgrePlatform, which should only build only the specific rendersystem.
- Same for other rendersystems (dummy, opengl)

The question is whether library built this way will be usable.

**Comment by Altren** [comment]
Library itself is platform agnostic, but our CMake build scripts are configured to always build some platform. To make it possible to build no or multiply platforms or platform without core some (not big) changes in build scripts are required.

**Comment by AMDmi3** [comment]
Ok, another related question: should platform modules be shared on static libraries? Are they loaded dynamically?

The one problem is that add_library commands for platform modules do not set whether libraries are shared or static while they should:

```
add_library(${PROJECTNAME} ${HEADER_FILES} ${SOURCE_FILES})
```

For me they are build static by default, however following

```
target_link_libraries(${PROJECTNAME} MyGUIEngine)
```

suggest that they should probably be shared instead. If they are loaded dynamically, there's no need to link them with MyGUIEngine, as the library will always be linked if they are used.

Also,

```
add_dependencies(${PROJECTNAME} MyGUIEngine)
```

seem to be useless in any case.

**Comment by Altren** [comment]
Platform modules are always static. *target_link_libraries* is not needed (you are right and there is no need to link MyGUIEngine), but add_dependencies must be there, since this static library technically depends on MyGUIEngine and can't be rebuild without it. For example if you change MyGUIEngine header you must rebuild MyGUIEngine with platform and without *add_dependencies* you can rebuild platform without MyGUIEngine.

**Comment by AMDmi3** [comment]
> Platform modules are always static.

Hmm, Debian seem to [ship](https://packages.debian.org/sid/amd64/libmygui.ogreplatform0debian1v5/filelist) shared libs for some reason. Could you maybe add STATIC to add_library to avoid misunderstanding?

> For example if you change MyGUIEngine header

Um, CMake does track header dependencies, isn't that enough? Header change will trigger rebuild of all source files that include it, and then all libraries that contain these sources, e.g. both MyGUIEngine and platforms.

**Comment by Altren** [comment]
It is not a problem to have platform to be built as .so, I can't recall all reasons, but as far as I remember it was easier to use it as static and also doesn't require to have another dynamic library with render and MyGUI linked into it. I guess they have some reasons to use it as shared and it's ok and have its pros and cons.

Having *add_dependencies* for static library doesn't do anything other than enforces build order.
CMake track changes, but if you change header in MyGUIEngine and call build *only* for platform without *add_dependencies* this might lead to inconsistent build, because MyGUIEngine will be built with old header. And with *add_dependencies* CMake will force MyGUIEngine build as well.

**Comment by AMDmi3** [comment]
> inconsistent build

IMO you get exactly what you should expect if you run build for platform only. Likewise, you can only run build for MyGUIEngine and not get platform rebuild and get the same inconsistency, that doesn't mean that engine should depend on platforms.

And if someone runs build for a specific subsystem, it's reasonable to expect he only wants to build the named subsystem. That's my case - for one package I want to build only MyGUIEngine and for other I only want to build (for example) dummy render system. So I've had to patch away all target_link_library and add_dependencies commands in Platform/**/CMakeLists.txt.

Anyway, I think I've solved my task, and summarizing I suggest to
- Add STATIC for platforms' add_libraries().
- Remove platforms' target_link_libraries() and add_dependencies().
