### ISSUE TITLE
Does MyGUI engine support multiple renderwindows?

### ISSUE THREAD

**Issue by niujingqian** [MyGUI/mygui#109]

**Comment by niujingqian** [comment]
if true;
one OgrePlatform for one renderwindow?
thanks!

**Comment by scrawl** [comment]
Not supported out of the box. Only one Platform can exist at a time.

But you can still do multiple windows by getting a little creative. Implement a custom Layer that draws to a secondary window. See the UnitTest_RTTLayer demo. Pretty much the same thing, except that your Layer would render to another Window instead of rendering to a texture.

All this can be done without changes to MyGUI itself, you just register your custom Layer implementation via the MyGUI factory.

**Comment by niujingqian** [comment]
thanks for your reply!
I had changed the engine for my use.
