### ISSUE TITLE
Relative mouse move inject, slow cursor when using SDL2 relative mode

### ISSUE THREAD

**Issue by fmj02** [MyGUI/mygui#144]
I've noticed a problem when using MyGUI with SDL2 and  SDL_SetRelativeMouseMode. The cursor movement is unbelievably slow, sluggish and unnatural, this only happens when using relative mouse mode of SDL2, except that everything is fine. My proposition is to add relative mouse injection. Just like it's possible with CEGUI. So maybe that would solve the problem somehow.

**Comment by scrawl** [comment]
You've closed the issue so maybe you've figured it out, but it does remind of an issue we had in OpenMW. In some configurations SDL was emitting many mouse movement events in a frame, and processing them one by one is of course slow. The solution was to merge all events from a single frame.

**Comment by enemyofthedawn** [comment]
@scrawl No I didn't figure it out. But I had no such issue with CEGUI. And that's the only thing that stopped me from using MyGUI in my project.

What do you mean to merge all events from a single frame?

**Comment by enemyofthedawn** [comment]
If that issue with cursor movement could be solved and cursor would move smoothly then the library would be pretty good.

**Comment by scrawl** [comment]
By merging the events I mean this: Let's say you poll all your SDL events for the current frame and you get 10 mouse movement events, each moving the mouse down by 1 pixel. You merge those events into a single event that moves the mouse by 10 pixels.
Processing lots of individual events could be slower, and once the game slows down a bit, the increased frame time is going to cause even <i>more</i> events per frame, slowing the game further, and so on.
Have you tried printing your mouse events to see what they're like and how many events you get in one frame?
The real cause is probably just your mouse event handler takes too long. It may or may not be a MyGUI issue. It might also be that you unnecessarily destroy and create widgets on every mouse movement (for example to update tooltips) and CEGUI is just faster at doing that than MyGUI is. 
I now recall the OpenMW change, it was this: https://github.com/OpenMW/openmw/pull/1366 but it was later reverted, because it caused an unrelated bug.

**Comment by scrawl** [comment]
I just re-read the first post, and I realized you say the cursor is sluggish, but not that the framerate dives, which is what my suggestions were aimed at.
Anyway, this is certainly some bug in your event handling and nothing to do with MyGUI. I can't be of more help without knowing your project.

**Comment by enemyofthedawn** [comment]
IIRC I was basing on this when implementing MyGUI: https://github.com/MyGUI/mygui/blob/e8de3e7b94d3e2c3333cf65737ada97d26a5fcd7/Common/Base/OpenGL/BaseManager.cpp
