### ISSUE TITLE
libCommon.so misses version number and install in cmake

### ISSUE THREAD

**Issue by ggardet** [MyGUI/mygui#157]
libCommon.so is built, but it misses version number and it does not install with CMake as other libs.

For the version numbering, we can do:
```
--- Common/CMakeLists.txt.orig	2016-03-05 07:17:23.175753455 -0600
+++ Common/CMakeLists.txt	2016-03-05 07:18:03.880751014 -0600
@@ -89,6 +89,7 @@
 endif()
 
 add_library(${PROJECTNAME} ${HEADER_FILES} ${SOURCE_FILES})
+set_target_properties(${PROJECTNAME} PROPERTIES VERSION ${MYGUI_VERSION} SOVERSION {MYGUI_VERSION_MAJOR})
 
 if(MYGUI_RENDERSYSTEM EQUAL 1)
 	add_dependencies(${PROJECTNAME} MyGUI.DummyPlatform)
```

**Comment by susnux** [comment]
Problem:

If compiled with `BUILD_SHARED_LIBS` `Common` is build as shared library, so it is linked dynamically into all programs (currently: tools, demos, unit tests).
So if you set the cmake options to install the demos / tools the library is missing.

Thats why the library needs to be installed or build explicitly as a module (on `add_library()`).

If you install that library on any of the common linux distributions (reason for installing, see above) it is required that any shared library is versioned, so that multiple versions can be installed at the same time (e.g. an old package is linked against an older versions can still be installed with a new packaged linked against a newer version of that library).
