### ISSUE TITLE
Performance problem In RenderItem Remove And Add

### ISSUE THREAD

**Issue by 36yang** [MyGUI/mygui#182]
When I Use the TabControl and  every tab has many widget, When I change between them, Now it  need many times. but  when I in the old MyGUI3.2.0 version.  It's very fast.   But I found it has  memory
leak problem.  now the  problem is fixed。  But now the time delay make me unwell。
I found the Performance problem  is in file "MyGUI_RenderItem.cpp"  function 
"void RenderItem::removeDrawItem(ISubWidget* _item)"   and  function
"void RenderItem::addDrawItem(ISubWidget* _item, size_t _count)"  when debug mode.。
Maybe  hash  map for DrawItems well performace better.

**Comment by Altren** [comment]
I don't see addDrawItem in profiler reports. Yes, removeDrawItem could be not so fast, but it seems, that there is no easy way to make it faster without decreasing render speed. hash_map would not fit, because we need to preserve order.
I tried to remove .erase call from the removeDrawItem, but in my test scenarios difference is barely visible.
Could you try to test it with https://github.com/MyGUI/mygui/tree/removeDrawItem_optimization branch? All changes are in RenderItem class.
Also please test in release mode, because there are several debug checks and asserts there.

**Comment by 36yang** [comment]
I have test it, now it's faster than before , But  still  slower than 3.20,  When in debug mode, change between Tab panel,  if the widget number is large, lt still can feel about 300ms delay in my computer,(before more than 1 second) .  But if in release mode, it nearly can't feel any delay,
