### ISSUE TITLE
CMake 3.16 or higher is required.

### ISSUE THREAD

**Issue by sercero** [MyGUI/mygui#197]
Hello @Altren, I have just tried compiling the latest changes you made to use as a base for the changes we discussed in OgrePlatform.

But I have found this onerous requirement that CMake should be a version equal or higher that 3.16.

Is this really necessary? (now I see that target_precompile_headers requires CMake 3.16)

Another thing that is failing now is SDL2.
SDL2_DIR="D:/OGRE2/Building/ogre-1.12.9/Dependencies/cmake"

But SDL2 is not installed there... and now the compilation fails:
```
D:/MyGUI/Sources/mygui-master/Common/Input/SDL/InputManager.h:11:10: fatal error: SDL2/SDL.h: No such file or directory
 #include <SDL2/SDL.h>
```

Thanks.

**Comment by Altren** [comment]
The only reason for the CMake 3.16 is a target_precompile_headers. While I felt that is might be an issue in some cases, I still feel that it worth it, because target_precompile_headers works really good and I'd rather recommend people updating to the CMake 3.16+. Do you think it would be better to do something like
```
if (${CMAKE_VERSION} VERSION_GREATER_EQUAL "3.16")
    target_precompile_headers(...)
endif ()
``` and remove version restriction?

I have deleted custom FindSDL.cmake script, because it wasn't working well in some cases. I'll see what can be done.

**Comment by sercero** [comment]
@Altren please do that.

I know it should be no big deal to update CMake but a simple if can solve the problem.

Thanks.

**Comment by Altren** [comment]
Fixed, also tested that 2.8.12 is actually supported.

**Comment by Altren** [comment]
Fixed SDL as well

**Comment by sercero** [comment]
Thanks
