### ISSUE TITLE
Can't #include "MyGUI_OpenGLRenderManager.h" due to "MyGUI_OpenGLImageLoader.h" not being installed

### ISSUE THREAD

**Issue by nopoe** [MyGUI/mygui#71]
While trying to build a MyGUI/OpenGL hello world program, I get the following error:

/usr/local/include/MYGUI/MyGUI_OpenGLRenderManager.h:14:37: fatal error:
MyGUI_OpenGLImageLoader.h: No such file or directory
#include "MyGUI_OpenGLImageLoader.h"

It seems like "make install" doesn't install the "MyGUI_OpenGLImageLoader.h" file (maybe because it isn't listed in "MyGUI.OpenGLPlatform.list"?)

The rest of the OpenGL platform headers are in /usr/local/include so I'm fairly certain I built MyGUI with the OpenGL platform correctly.

**Comment by colesnicov** [comment]
Hi guys. Maybe you would like to restore the packages in the repositories for Ubuntu. File "**MyGUI_OpenGLImageLoader.h**" **in distribution is still missing** and it is impossible MyGUI use it ... I had to manually compile and it took me all day today. As a beginner with MyGUI I was very unhappy. It's many many many works around it. **Also, when you compile as a static library with it in my application failed to integrate. I viewed our deliberations: libdl.so: error adding symbols: DSO missing from the command line. So I had to uncheck the option static and it all went.** Now I must devote documentation. Do you happen tutorials in Russian or Czech? :) Oh, and I had to abandon the installation examples and tools because **it's still trying to find the file "windows.h"** (_Common/Base/OpenGL/BaseManager.h_ and _Common/Base/OpenGL/BaseManager.cpp_) **who on Linux is not understandable!** Well, I wanted to write to you that you knew it. So my OS is Ubuntu 4.16 Google translate helped me write this letter. Thank you. 

> P.S. It's quite a shame that I could not compile MyGUI / tools, the font editor, layout editors and other utilities I probably will miss it.
