### ISSUE TITLE
shared_ptr causing compiling failure in Mac

### ISSUE THREAD

**Issue by xzwang2005** [MyGUI/mygui#80]
In Mac, majority of the compiling issues are related to the customized version shared_ptr<T> class, particularly when compared to nullptr with '==' or '!=' operators.  However, the same code compiles fine in Windows and Linux (any ideas?).

Here's some fixes I can think of:
1) overload the operators - it did work based on my test, but prone to bug implementing a smart pointer
2) use std::shared_ptr<> - require more changes in the code base, any may not compile on older compilers, but much more reliable
3) somehow modify cmake script to make clang behave the save as gnu compiler so that the errors just go away ?  don't know how though

any thoughts?

**Comment by scrawl** [comment]
I just pushed a 'sharedptr' branch defining some comparison operators for shared_ptr <-> raw pointer comparisons. Does that work?

**Comment by xzwang2005** [comment]
I forgot to mention, operator= also need to be overloaded.  Btw, why the original code works in Windows and Linux?

**Comment by scrawl** [comment]
> Btw, why the original code works in Windows and Linux?

Because of implicit conversions, I think.

<pre>
		shared_ptr(T* p) : ptr(p), count(new unsigned(1)) { }
</pre>

Does your compiler have the "nullptr" (C++11) keyword available? 

By default nullptr in MyGUI is just defined as 0, but in C++11 nullptr has some new semantics. I'm thinking those semantics might not work with the implicit conversions. Perhaps we need to add a new constructor, like so:

<pre>
		shared_ptr(nullptr p) : ptr(p), count(new unsigned(1)) { }
</pre>

But then we'd also need to guard the constructor to check for the availability of C++11. So defining the new comparison operators might be the easier fix.

**Comment by scrawl** [comment]
>  I'm thinking those semantics might not work with the implicit conversions.

To expand on this.

If I write:
```
shared_ptr<A> a;
if (a == nullptr)
```
A C++11 compiler would need to perform *two* implicit conversions:
```nullptr``` -> ```A*```
```A*``` -> ```shared_ptr<A>```

However, only one implicit conversion can be performed at a time. That is why the code does not compile with the nullptr keyword.

With a pre-c++11 compiler, where we have
<pre>
#define nullptr 0
</pre>
everything works fine, since '0' is already a pointer literal.
```A*``` -> ```shared_ptr<A>```

**Comment by scrawl** [comment]
New commit on sharedptr branch: I renamed the nil() method and added operator=. Does it work now?

**Comment by xzwang2005** [comment]
in Singleton header:

#if MYGUI_COMPILER == MYGUI_COMPILER_MSVC || MYGUI_PLATFORM == MYGUI_PLATFORM_APPLE
	template <class T>
	class Singleton
#else
	template <class T>
	class MYGUI_EXPORT Singleton
#endif

Fix:  remove " || MYGUI_PLATFORM == MYGUI_PLATFORM_APPLE" 

in Common/Cmakelists.txt, toward the end:
if(NOT WIN32)
	if(UNIX)
		find_package(X11)
		target_link_libraries(${PROJECTNAME} X11)
		include_directories(${X11_INCLUDE_DIR})
	endif(UNIX)
endif()

Fix: change if(UNIX) to if(NOT APPLE)  -- I guess Apple is considered a unix-like os in cmake.

Most demos and all editors should compile then, except for the plugin demo and the renderbox demo.  I'll double check later after these changes are committed.

**Comment by scrawl** [comment]
Ok, I committed these two changes and merged the sharedptr branch.
