### ISSUE TITLE
Not working fonts on GL3 rendereer+Bug with depth

### ISSUE THREAD

**Issue by galek** [MyGUI/mygui#91]
Hi

Somebody can reply about GL3Renderer. It's my bug or no?

+ Depth detection bug:
void OpenGL3RenderManager::setViewSize(int width, int height)
Replace param 1 in mInfo.maximumDepth = 1 on 0. Or you will see this:
http://images.gameru.net/image/direct/adbb8a70e3.jpg

**Comment by scrawl** [comment]
You need to render MyGUI after rendering your scene. If you do it the other way around, then I suppose setting MyGUI's depth to 0 will "fix" things as far as your scene no longer drawing on top of MyGUI (since it will now fail the depth test) - but widget transparency won't work then.

Just render in following order:
1. 3D scene
2. MyGUI

**Comment by galek** [comment]
Ok, it's correct, but fonts is still not working

**Comment by scrawl** [comment]
Open a new issue please.
